services:
  geth:
    image: bdimitrov93/go-ethereum:latest 
    container_name: devnet
    command:
    - --dev 
    - --http 
    - --http.api=eth,web3,net 
    - --http.addr=0.0.0.0
    - --http.port=8545 
    - --http.corsdomain='*'
    ports:
      - "8545:8545"    
      - "30303:30303"  
    volumes:
      - geth-data:/root/.ethereum
    networks:
      - gethnet

volumes:
  geth-data:

networks:
  gethnet:

